language: python
python:
  - "3.6"
before_install:
  - "sudo apt-get install python-dev"
  - ./download_etcd.sh 2.3.7
install:
  - pip install -r requirements.txt
  - pip install pytest pytest-cov codecov flake8 mypy
before_script:
  - nohup ./bin/etcd &
script:
  - flake8 doge
  - mypy doge
  - pytest --cov=./
after_success:
  - codecov